"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def env_flag(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(int(default))).lower() in {"1", "true", "yes", "on"}


# Set DJANGO_SECRET_KEY in every persistent environment. The generated local
# fallback avoids a hard-coded secret but invalidates sessions after a restart.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', get_random_secret_key())

# Secure-by-default: local debugging must be deliberately enabled.
DEBUG = env_flag('DJANGO_DEBUG')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'onboarding',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.middleware.LocalNullOriginCsrfMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'ikano_onboarding'),
        'USER': os.environ.get('POSTGRES_USER', os.environ.get('USER', 'postgres')),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Django's built-in static server is convenient locally but must be disabled
# behind a production static-file server/CDN.
SERVE_STATIC_FILES = env_flag('DJANGO_SERVE_STATIC_FILES', default=True)


# ---------------------------------------------------------------------------
# Security controls
# ---------------------------------------------------------------------------

# Cookies remain usable over HTTP for local development. Set
# DJANGO_SECURE_COOKIES=1 and DJANGO_FORCE_HTTPS=1 behind HTTPS in production.
SECURE_COOKIES = env_flag('DJANGO_SECURE_COOKIES')
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = SECURE_COOKIES
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = SECURE_COOKIES
CSRF_COOKIE_SAMESITE = 'Lax'
# Explicit local origins keep the development server usable from the embedded
# browser while production deployments can override this list through env.
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://127.0.0.1:8000,http://localhost:8000',
).split(',')
CSRF_FAILURE_VIEW = 'onboarding.views.csrf_failure'
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'no-referrer'  # prevents resume tokens leaking via Referer headers
SECURE_SSL_REDIRECT = env_flag('DJANGO_FORCE_HTTPS')
SECURE_HSTS_SECONDS = 31_536_000 if SECURE_SSL_REDIRECT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SECURE_HSTS_PRELOAD = SECURE_SSL_REDIRECT

# A shared cache such as Redis should replace this local cache in production.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'onboarding-security',
    }
}


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ---------------------------------------------------------------------------
# Onboarding app settings
# ---------------------------------------------------------------------------

# How long a resume magic link stays valid after being issued.
RESUME_TOKEN_TTL_HOURS = int(os.environ.get('RESUME_TOKEN_TTL_HOURS', '72'))

# An in-progress application with no activity for this long is treated as
# abandoned the next time it is touched (checked on access; a periodic job
# would be the production approach for proactive cleanup).
ABANDONED_AFTER_HOURS = int(os.environ.get('ABANDONED_AFTER_HOURS', '24'))

# Limit token guesses from one source address. The value is intentionally
# modest for a demo; production should use a shared cache and edge rate limit.
RESUME_MAX_ATTEMPTS = int(os.environ.get('RESUME_MAX_ATTEMPTS', '10'))
RESUME_ATTEMPT_WINDOW_SECONDS = int(os.environ.get('RESUME_ATTEMPT_WINDOW_SECONDS', '900'))
