# Generated by Django 6.1 on 2026-08-25 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('SE', 'Sweden'), ('ES', 'Spain'), ('PL', 'Poland')], max_length=2)),
                ('account_type', models.CharField(choices=[('individual', 'Private individual'), ('business', 'Business')], max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('manual_review', 'Manual review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='in_progress', max_length=16)),
                ('current_step_key', models.CharField(blank=True, max_length=64)),
                ('resume_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('resume_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('decision_outcome', models.CharField(blank=True, max_length=16)),
                ('decision_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(max_length=48)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='onboarding.application')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('check_type', models.CharField(max_length=32)),
                ('step_key', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_results', to='onboarding.application')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_key', models.CharField(max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='onboarding.application')),
            ],
            options={
                'ordering': ['completed_at'],
                'unique_together': {('application', 'step_key')},
            },
        ),
    ]
